#!/usr/bin/env bash
# Displays information about subdomains

if [ "$#" = 1 ]
then
    subdomains=("www" "lb-01" "web-01" "web-02")
    for sub_domain in "${subdomains[@]}"
    do
        record_type=$(dig "$sub_domain.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
        ip_address=$(dig "$sub_domain.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')
        echo "The subdomain $sub_domain is a $record_type record and points to $ip_address"
    done
elif [ "$#" = 2 ]
then
    record_type=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
    ip_address=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')
    echo "The subdomain $2 is a $record_type record and points to $ip_address"
fi