#!/usr/bin/env bash

# Function to display subdomain information
display_info() {
    local sub_domain=$1
    local record_type=$(dig +short -t ANY "$sub_domain.$domain" | awk 'NR==1{print $4}')
    local destination=$(dig +short "$sub_domain.$domain" | head -n 1)

    echo "The subdomain $sub_domain is a $record_type record and points to $destination"
}

# Main script logic
if [ "$#" -eq 1 ]; then
    # Display information for default subdomains
    domain=$1
    display_info www
    display_info lb-01
    display_info web-01
    display_info web-02
elif [ "$#" -eq 2 ]; then
    # Display information for specified subdomain
    domain=$1
    sub_domain=$2
    display_info $sub_domain
else
    # Display usage message for incorrect number of arguments
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi
