#!/usr/bin/env bash
# 100-redirect_http_to_https

frontend www-http
    bind *:80
    mode http
    redirect scheme https code 301 if !{ ssl_fc }

frontend www-https
    bind *:443 ssl crt /etc/haproxy/certs/www.pem
    reqadd X-Forwarded-Proto:\ https
    default_backend www-backend

backend www-backend
    server web-server 127.0.0.1:80
