#!/usr/bin/env bash
# Bash script to configure Nginx for a 301 redirect on /redirect_me

# Ensure Nginx is installed
sudo apt-get update
sudo apt-get install -y nginx

# Create a custom Nginx configuration file for the redirection
echo "server {
    listen 80;
    server_name localhost;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        root /var/www/html;
        index index.html index.htm;
    }
}" | sudo tee /etc/nginx/sites-available/redirect_me > /dev/null

# Create a symbolic link to enable the new site
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Remove the default Nginx configuration
sudo rm /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
sudo service nginx restart