#!/usr/bin/env bash
# Configures a new ubuntu machine by installing

# Update package information
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create custom 404 page
sudo mkdir -p /usr/share/nginx/html
sudo echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html

# Configure Nginx with custom 404 page
sudo printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}" | sudo tee /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
