#!/usr/bin/env bash
# shellcheck disable=SC2154
# Configures a new Ubuntu machine with Nginx

# Update package list
sudo apt-get update

# Install Nginx
sudo apt-get install nginx -y

# Allow Nginx HTTP traffic
sudo ufw allow 'Nginx HTTP'

# Set default Nginx page
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html

# Configure redirection
new_string="listen 80 default_server;\\n\\tlocation \/redirect_me {\\n\\t\\treturn 301 https:\/\/www.youtube.com\/;\\n\\t}"
sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html

# Configure 404 error page
new_string="listen 80 default_server;\\nerror_page 404 \/404.html;\\n\\tlocation = \/404.html {\\n\\t\\troot \/usr\/share\/nginx\/html;\\n\\t\\tinternal;\\n\\t}"
sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Add custom header to HTTP response
new_string2="http {\\n\\tadd_header X-Served-By \"$HOSTNAME\";"
sudo sed -i "s/http {/$new_string2/" /etc/nginx/nginx.conf

# Start Nginx service
sudo service nginx start
