#!/usr/bin/env bash
# Configures Nginx to include a custom header in its HTTP response

# Update package list
sudo apt-get update

# Install Nginx
sudo apt-get install nginx -y

# Create custom configuration file
echo "add_header X-Served-By \$HOSTNAME;" | sudo tee /etc/nginx/conf.d/01-custom-header

# Restart Nginx to apply changes
sudo service nginx restart
