#!/usr/bin/env bash
# Script: 1-debugging_made_short
sed -i "s/8080/80/g" /etc/nginx/sites-available/default
service nginx restart
service nginx status | grep -q "nginx is running" || echo "nginx is not running"
