#!/usr/bin/env bash
# This script displays information about users from the /etc/passwd file using a while loop and IFS.

# Set IFS to colon (:) to split fields in /etc/passwd
IFS=":"

# Read the /etc/passwd file line by line using a while loop
while read -r username password uid gid user_info home_directory shell; do
    # Print the user information in the desired format
    echo "The user $username is part of the $gid gang, lives in $home_directory, and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $user_info"
done < /etc/passwd
