#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using an until loop

# Initialize a counter
counter=0

# Use an until loop to display "Best School" 10 times
until [ $counter -ge 10 ]; do
    echo "Best School"
    ((counter++))
done
