#!/usr/bin/env bash
# Bash script to display all active IPv4 IPs on the machine

# Use ifconfig to get network interface information and grep for IPv4 addresses
ifconfig | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | grep -v "127.0.0.1"