#!/usr/bin/env bash
# Description: Run the whoami command under the specified user.

if [ $# -eq 0 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

username=$1

# Run whoami command under the specified user
sudo -u "$username" whoami
