#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080.

# Stop Nginx service
service nginx stop

# Update Nginx configuration to run as nginx user
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Update Nginx default site configuration to listen on port 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Set appropriate permissions for nginx.conf
chmod 644 /etc/nginx/nginx.conf

# Start Nginx service
sudo -u nginx service nginx start
